# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Test

on: #When this workflow is executing, in this case when a push is done to main
  push:
    branches: [ "main" ]


permissions: #Permissions needed, permissions to read the content
  contents: read

jobs: # What this CI/CD pipeline need to execute
  build_and_test:

    runs-on: ubuntu-latest #Take an ubuntu image, and create a container

    steps: # What are the steps job will do
    - uses: actions/checkout@v4 #Do a checkout of the branch
    - name: Set up Python 3.10 # Install python intance
      uses: actions/setup-python@v3 # Install python intance
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with Ruff
      run: ruff check .     
    - name: Test with pytest
      run: pytest test.py 